### ISSUE TITLE
Lat/Long to XY Conversion

### ISSUE THREAD

**Issue by compdesigner-nz** [blueherongis/Heron#36]
Hey Team,

I'm using the Decimal Degree to XY component and am receiving an error where the long long values combine to create a point where the corresponding x and y values are the same as the lat long values

![image](https://user-images.githubusercontent.com/91602118/145898529-8c130f26-1754-403b-89ee-9375c8eee099.png)

It was working in a previous version of a file that I am using and so I versioned back to that version of the file (I'm using git) and the issue is still the same. I am working in meters in Rhino.

Not sure what the error is exactly, but it would be great if you could please look into it!

**Comment by blueherongis** [comment]
Have you set the Earth Anchor Point prior to plugging the Lat/Lon into the DDtoXY component?

**Comment by compdesigner-nz** [comment]
I didn't realise that I needed the EPSG reference number to project the points. All good now :)
