### ISSUE TITLE
Installing Heron components for use in Rhino 6

### ISSUE THREAD

**Issue by jamiedtor** [blueherongis/Heron#38]
I'm hoping to incorporate Heron into a new work flow I'm developing in Rhino.  I'm a relative newbie to the software.  I see that this is much more up to date than the components on Food for Rhino, but I'm at a bit of a loss when it comes to actually downloading and installing the Heron components from here.  Is there somewhere online with a tutorial on how to do so? Thanks so much!

**Comment by blueherongis** [comment]
Hi @jamiedtor, I recommend installing the latest version of Heron by using the "TestPackageManager" command in Rhino 6 and "PackageManager" in Rhino 7.  You can also download v0.3.8 from the Releases here on github https://github.com/blueherongis/Heron/releases/tag/v0.3.8.  This will be a zip file that you should unblock and install as you would if you were downloading from food4rhino.  Let me know if you have any trouble with either of these methods.

**Comment by jamiedeweese** [comment]
> Hi @jamiedtor, I recommend installing the latest version of Heron by using the "TestPackageManager" command in Rhino 6 and "PackageManager" in Rhino 7. You can also download v0.3.8 from the Releases here on github https://github.com/blueherongis/Heron/releases/tag/v0.3.8. This will be a zip file that you should unblock and install as you would if you were downloading from food4rhino. Let me know if you have any trouble with either of these methods.

This worked perfectly! Thanks so much.

**Comment by jamiedtor** [comment]
Just closing it out because I forgot to earlier.  Thanks.
