### ISSUE TITLE
SRTM DEM download fails

### ISSUE THREAD

**Issue by jamiedeweese** [blueherongis/Heron#42]
When trying to use the RESTTopo component for either of the SRTM options or the ALOS World 3D, I get different errors:

1. Solution exception:The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Other times, I get: 

1. Solution exception:The remote server returned an error: (401) Unauthorized.

![Screenshot 2022-05-22 120403](https://user-images.githubusercontent.com/56725898/169704793-a1d3f286-4ba6-4f24-9d88-2873909b94a4.png)

I feel like this must be user error, but I'm not sure how to correct it.

**Comment by blueherongis** [comment]
I believe this error is related to the source of the SRTM data, [OpenTopography.org](https://opentopography.org/), recently changing it's policy and requiring an API key.  I've embedded a key in Heron v0.3.9 and it should be working properly.  Can you verify which version of Heron you are using?  Also, try the other sources available in the menu and let me know if any of those throw an error.
