### ISSUE TITLE
Error Importing USGS 3DEP DEM

### ISSUE THREAD

**Issue by rchou-kpf** [blueherongis/Heron#44]
Hello, 
First of all, thank you for creating this amazing plugin! 

I'm having issues importing USGS 3DEP DEM using the "Get REST Topography" Component -- Getting the `1. Solution exception:Index (zero based) must be greater than or equal to zero and less than the size of the argument list.` Error.

Strangely enough, It had worked for me just a couple of weeks ago, and I have not modified the script since then.  

Thank you for your help!

**Comment by blueherongis** [comment]
I'm glad you like it!  What version of Heron are you running?  And can you either post your definition or a screenshot?

**Comment by rchou-kpf** [comment]
Hi,

Of course. Please see attached. (Attaching gh file as a zip because .gh not supported on Github)

![error](https://user-images.githubusercontent.com/71403886/1
[Heron_Import_DEM.zip](https://github.com/blueherongis/Heron/files/9205031/Heron_Import_DEM.zip)
81411393-fb8f88aa-59a6-4f81-8f8d-a88461fd9689.PNG)

**Comment by blueherongis** [comment]
I see now that I had modified the 3DEP end point query to enable a custom SRS.  This was done as part of the Heron SRS feature I'm currently working on where you can have Heron work in any SRS you'd like.  The https://github.com/blueherongis/Heron/commit/390b71503765791c1f0b97e2a2955ca76585d79b commit that changed the query: 

![image](https://user-images.githubusercontent.com/13613796/181567479-6dfd78df-51e0-421f-b59e-4056b0c88749.png)

I have reverted back to get the 3DEP service working again.  Let me know if this worked for you.

**Comment by rchou-kpf** [comment]
that solved it. Thank you!
