### ISSUE TITLE
SetEAP not working with Lat/Lon input

### ISSUE THREAD

**Issue by blueherongis** [blueherongis/Heron#46]
See issue here:
https://discourse.mcneel.com/t/re-heron-set-spacial-reference-system/150430/3?u=brian_washburn

Likely has something to do with the component regex not interpreting decimal degrees correctly.

**Comment by ChristopherConnock** [comment]
I can't see the issue with the link, but is this referring to this error when a text string is given as input to SetEAP LAT and LON?

![image](https://user-images.githubusercontent.com/1145313/202553181-5de38317-285a-4da6-8bd8-371ddc5260b0.png)

**Comment by blueherongis** [comment]
Yes, you've reproduced the error.  I think it's the fact that the regex [here](https://github.com/blueherongis/Heron/blob/4222f99bdacde5c1d3bc8d030b0215a8791e53ce/Heron/Convert.cs#L979) was limited to 12 decimal places.  The regex is new since v0.4.0 to allow DMS input instead of just DD.  I'm going to increase the regex to 20 decimal places.

https://github.com/blueherongis/Heron/blob/4222f99bdacde5c1d3bc8d030b0215a8791e53ce/Heron/Convert.cs#L979
